export enum ErrorsEnum {
  E_EMAIL_ALREADY_EXISTS = -1,
  E_NON_EXISTING_TEACHER = -2,
  E_CLASS_ALREADY_ASSIGNED = -3,
  E_BAD_PASSWORD = -4,
  E_NO_EXISTING_EMAIL = -5,
  E_EXPERT_FOR_SAME_SCHOOL = -6,
  E_EXPERT_FOR_DIFFERENT_SCHOOL = -7
}
